version: '2'

services:
  postgres:
    image: postgres:11.7
    container_name: authz-demo-keycloak
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    ports:
      - "5432:5432"

  keycloak:
    image: keycloak-authz-demo:1.0-SNAPSHOT
    container_name: authz-demo-keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      DB_VENDOR: postgres
      DB_ADDR: postgres
    command: -Dkeycloak.profile.feature.scripts=enabled
    ports:
      - "8180:8080"
    depends_on:
      - postgres
